### ISSUE TITLE
error with epoch 1.0.7

### ISSUE THREAD

**Issue by RedLink-kam** [BigEgg17/Epoch-Antihack-Admin-Tools#1]
Hello.
When use your Tools in RPT i see that:
23:18:20 Error in expression <[parseNumber ctrlText(_this select 0), "cashMoney", 'wallet'] call AH_fnc_adjust>
23:18:20   Error position: <cashMoney", 'wallet'] call AH_fnc_adjust>
23:18:20   Error Missing ]
23:18:20 Error in expression <[parseNumber ctrlText(_this select 0), "cashMoney", 'wallet'] call AH_fnc_adjust>
23:18:20   Error position: <cashMoney", 'wallet'] call AH_fnc_adjust>
23:18:20   Error Missing ]

**Comment by BigEgg17** [comment]
Please reference this [commit](https://github.com/BigEgg17/Epoch-Antihack-Admin-Tools/commit/5e638584941d2b9cff71cc835fe03f8c970d6b0b) and let me know if the issue persists after applying the change.
