### ISSUE TITLE
Stuck on Authenticating server

### ISSUE THREAD

**Issue by cyberdemonv2** [BigEgg17/Epoch-Antihack-Admin-Tools#13]
i am getting the following error in my server RPT whenever i try to ad any kind of admin in config.sqf, it is current set as:

local _mod = []; //---Add moderators here - don't forget commas!
local _admin = ["not my real ID", "myguid in here", false, false, true, ""]; //---Add admins here - don't forget commas!
local _headAdmin = []; //---Add head admins here - don't forget commas!
local _owner = [];//---Add owners here - don't forget commas!

17:22:17 "<Epoch-AH>: Initializing Epoch Antihack/Admin Tools"
17:22:17 "<Epoch-AH>: Config loaded successfully"
17:22:17 "<Epoch-AH>: Global ban sync initiated"
17:22:17 Error in expression <elect _forEachIndex;
{
local _name = _x select 0;
local _puid = _x select 1;
loc>
17:22:17   Error position: <select 0;
local _puid = _x select 1;
loc>
17:22:17   Error select: Type String, expected Array,Config entry
17:22:17 File z\addons\dayz_server\antihack\antihack.sqf, line 32

i have tried multiple ways as shown in your examples, but it just will not work for me, unless i leave all admin sections empty, or as include on a fresh download!

**Comment by ZzBombardierzZ** [comment]
You are adding admin wrong. Do this:
local _admin = [
**[**"not my real ID", "myguid in here", false, false, true, ""**]**
];

(add an extra [ ] on each side)

Also I advise making yourself owner. Admin doesn't get very much power.

**Comment by BigEgg17** [comment]
Please see above - this is an admin formatting issue in your config.
