### ISSUE TITLE
Add support UTF-8 (if you can)

### ISSUE THREAD

**Issue by TheFirstNoob** [BigEgg17/Epoch-Antihack-Admin-Tools#19]
Hello. Standart LOGS files (english) didnt have problem to sent UTF-8 messages. But if trying to translate russian... well...
`19.7.2022 3:37:49  | [BE]First (76561198072428132): РћС‚РїСЂР°РІР»РµРЅ "[BE]First (76561198072428132)" РІ РѕРєРµР°РЅ | Uptime: 00:02:42 РљР°СЂС‚Р°: 24-Napf`
All text brokens.

Can correct this or give some Idea how to fix w\o edit DLL src.

**Comment by BigEgg17** [comment]
What text editor are you using to read the logs?

**Comment by TheFirstNoob** [comment]
Notepad++

**Comment by BigEgg17** [comment]
Please download the most recent DLL/Antihack.ini files and change the encoding to UTF-8 and report back. Special thanks to @IsGoose

**Comment by TheFirstNoob** [comment]
So... I update dll and ini, but now logs didnt create on Lan and Host. I recheck many times roots and other but all fine. Logs didnt creating.

**Comment by TheFirstNoob** [comment]
I replace dll to old. In Old DLL logs creating and works. Something in New DLL.

**Comment by IsGoose** [comment]
> I replace dll to old. In Old DLL logs creating and works. Something in New DLL.

I will take a look, the environment I used to test was different to a real use case, I will debug further and get back to you
Regards

**Comment by BigEgg17** [comment]
@TheFirstNoob please try the rebuilt version of the DLL provided by @IsGoose (he pushed this last night).

Thanks

**Comment by TheFirstNoob** [comment]
Nope. Still broken on me... In RPT translate (ru) working fine.
https://drive.google.com/file/d/1VGBnHOSFb4UVI5yJMljRgYfPVp-2eMLu/view?usp=sharing

I upload my files with Translate on drive. Maybe this help u for test and other.
I trying reinstall Language system files later. Maybe some broke on me (but all other edited files work fine)

.log support UTF in default? What if you try to convert Write system to TXT?

**Comment by IsGoose** [comment]
What part of it is broken? The DLL loaded & logged just fine for me, last night

**Comment by TheFirstNoob** [comment]
logs created fine but encoding still text in logs (with utf8 in .ini) broken.

`3.9.2022 8:37:52  | [BE]First (76561198072428132): Enabled РѕС‚РєР»СЋС‡РёС‚СЊ Р°РіСЂРµСЃСЃРёСЋ Р·РѕРјР±Рё @ 089170 | Uptime: 00:00:51 РљР°СЂС‚Р°: 24-Napf`

**Comment by IsGoose** [comment]
With Notepad++, what encoding  is the file? It will show it in the bottom right

**Comment by TheFirstNoob** [comment]
Notepad++ set to UTF-8 by default on my settings.

**Comment by IsGoose** [comment]
When you open a file with notepad++ it will tell you the encoding of the file itself, if it says its UTF8 then the issue lies elsewhere and not in the Logging DLL

**Comment by TheFirstNoob** [comment]
I redownload original sqf files and Notepad telling me UTF-8 (default for file).
I will look for the problem at my system but with other files when translating everything is ok. Oddities. In any case, thanks for the help.

**Comment by IsGoose** [comment]
With the UTF8 option in the Antihack.ini the DLL will write a UTF8 file regardless of your system default.
I will take a look at your example and see if I can do anything else, there might be an issue elsewhere that might be out of our control

**Comment by IsGoose** [comment]
Okay, I have done some more testing, it seems that this will not work with Special Russian Characters when the Extension is tested with Arma 2, however when using the Test Console Provided in the Repo it works just fine and as Intended.
Test String: `Любя, съешь щипцы, — вздохнёт мэр, — Кайф жгуч!`
Arma Output: ` ` (no joke, literally just a space)
Test Console: `Любя, съешь щипцы, — вздохнёт мэр, — Кайф жгуч!`
I would hazard a guess and say that the way the Engine passes the String over callExtension does not support certain Characters, and/or the way in which the Extension Receives the String does not support Special Characters. Theres no way to know for sure, and it seems this issue is out of our control.

These Special Characters would work with the RPT (Example, `diag_log`) because the Engine Itself will Log it, and there's no special passing of the String, rather just a raw write to file, whereas passing over `callExtension` it is handled differently

Sorry We could not fix your issue, it appears out of the DLLs control

Regards

**Comment by IsGoose** [comment]
To elaborate, when the `callExtension` String Parameter is passed to the DLL, it has to be Marshaled using an LPStr, which is a Pointer to an array of 8 Bit Characters (1 byte each).
But Unicode Characters (after the first 128 Unicode Characters), are more than 1 Byte, so they are essentially lost with Marshaling.
We cannot work around this Unfortunately, a C++ Logging DLL might be able to help you out however

Regards

**Comment by TheFirstNoob** [comment]
You mean this DLL? https://github.com/oiad/scripts/tree/master/fnc_log
Or you mean create new dll?

**Comment by TheFirstNoob** [comment]
ooookkkeeeyyy... I fix this problem on my Windows 11.
My OS uses the wrong encoding format (Windows 1251) but it should Windows 1252.
Now all logs work correctly with this dll on Both encoding parametrs (system and utf8).

`3.9.2022 8:37:52  | [BE]First (76561198072428132):  Включена функция - отключить агрессию зомби @ 089170 | Uptime: 00:00:51 Карта: 24-Napf`

Thank you so much for your response and help in this situation, as well as thanks for the time and nerves spent
