### ISSUE TITLE
Error RPT Epoch 1.0.7

### ISSUE THREAD

**Issue by ZizionarD** [BigEgg17/Epoch-Antihack-Admin-Tools#2]
Hello.
After installation, errors occur:
```
11:26:25 Error in expression <f (_ver == "1.0.6.2") then {
_cashvar = Z_MoneyVariable;
} else {
_cashvar = if >
11:26:25   Error position: <Z_MoneyVariable;
} else {
_cashvar = if >
11:26:25   Error Undefined variable in expression: z_moneyvariable
11:26:25 File z\addons\dayz_server\antihack\antihack.sqf, line 22
```
```
11:26:25 Error in expression <_bankvar = if (_ver == "1.0.6.2") then {Z_BankVariable} else {"bankMoney"};

dia>
11:26:25   Error position: <Z_BankVariable} else {"bankMoney"};

dia>
11:26:25   Error Undefined variable in expression: z_bankvariable
11:26:25 File z\addons\dayz_server\antihack\antihack.sqf, line 27
```
```
11:26:25 Error in expression <"_hide", "_logs", "_exec"];

_name = _x select 0;
_puid = _x select 1;
_hide = _>
11:26:25   Error position: <select 0;
_puid = _x select 1;
_hide = _>
11:26:25   Error select: Type String, expected Array,Config entry
11:26:25 File z\addons\dayz_server\antihack\antihack.sqf, line 54
```

**Comment by BigEgg17** [comment]
Are you running on 1.0.7? If so, please change _ver in config.sqf to 1.0.7

**Comment by ZizionarD** [comment]
> Are you running on 1.0.7? If so, please change _ver in config.sqf to 1.0.7

I changed the value to 1.0.7, but the last error still remained
```
23:37:56 Error in expression <"_hide", "_logs", "_exec"];

_name = _x select 0;
_puid = _x select 1;
_hide = _>
23:37:56   Error position: <select 0;
_puid = _x select 1;
_hide = _>
23:37:56   Error select: Type String, expected Array,Config entry
23:37:56 File z\addons\dayz_server\antihack\antihack.sqf, line 54
```

**Comment by BigEgg17** [comment]
> > Are you running on 1.0.7? If so, please change _ver in config.sqf to 1.0.7
> 
> I changed the value to 1.0.7, but the last error still remained
> 
> ```
> 23:37:56 Error in expression <"_hide", "_logs", "_exec"];
> 
> _name = _x select 0;
> _puid = _x select 1;
> _hide = _>
> 23:37:56   Error position: <select 0;
> _puid = _x select 1;
> _hide = _>
> 23:37:56   Error select: Type String, expected Array,Config entry
> 23:37:56 File z\addons\dayz_server\antihack\antihack.sqf, line 54
> ```

Please look at the config format for admins. You need to add them in an array like the example provides
