### ISSUE TITLE
RPT Errors

### ISSUE THREAD

**Issue by cyberdemonv2** [BigEgg17/Epoch-Antihack-Admin-Tools#3]
running a 1.0.7 pre-release server, and getting getting a few errors in my RTP :

13:22:39 Error in expression <	if (str DZE_RestrictSkins != str "+str DZE_RestrictSkins+") then {throw 'DZE_Re>
13:22:39   Error position: <DZE_RestrictSkins+") then {throw 'DZE_Re>
13:22:39   Error Undefined variable in expression: dze_restrictskins
13:22:39 File z\addons\dayz_server\antihack\antihack.sqf, line 892
13:22:39 Error in expression <6}]];
");

if (_mic) then {_AH_Normal = _AH_Normal + ("
	[] spawn {
		waitUntil >
13:22:39   Error position: <_AH_Normal + ("
	[] spawn {
		waitUntil >
13:22:39   Error Undefined variable in expression: _ah_normal
13:22:39 File z\addons\dayz_server\antihack\antihack.sqf, line 939
13:22:39 "<Epoch-AH>: Normal client compiled successfully"
13:22:39 Error in expression <indDisplay 46}]];
	");
};

_AH_Normal = _AH_Normal + ("
	if (("+_kfc_info+" sele>
13:22:39   Error position: <_AH_Normal + ("
	if (("+_kfc_info+" sele>
13:22:39   Error Undefined variable in expression: _ah_normal
13:22:39 File z\addons\dayz_server\antihack\antihack.sqf, line 910
13:22:40 "<Epoch-AH>: Staff client compiled successfully"
13:22:40 "<Epoch-AH>: SERVER: Created 156 safe zone bubbles"
13:22:40 "<Epoch-AH>: SERVER: Processing mission files..."
13:22:40 Error in expression < {_arr set [_i, 0]};
			_file = toArray(preprocessFile _x);

			{_x = _x min 128>
13:22:40   Error position: <preprocessFile _x);

			{_x = _x min 128>
13:22:40   Error preprocessfile: Type Array, expected String13:22:39 Error in expression <	if (str DZE_RestrictSkins != str "+str DZE_RestrictSkins+") then {throw 'DZE_Re>
13:22:39   Error position: <DZE_RestrictSkins+") then {throw 'DZE_Re>
13:22:39   Error Undefined variable in expression: dze_restrictskins
13:22:39 File z\addons\dayz_server\antihack\antihack.sqf, line 892
13:22:39 Error in expression <6}]];
");

if (_mic) then {_AH_Normal = _AH_Normal + ("
	[] spawn {
		waitUntil >
13:22:39   Error position: <_AH_Normal + ("
	[] spawn {
		waitUntil >
13:22:39   Error Undefined variable in expression: _ah_normal
13:22:39 File z\addons\dayz_server\antihack\antihack.sqf, line 939
13:22:39 "<Epoch-AH>: Normal client compiled successfully"
13:22:39 Error in expression <indDisplay 46}]];
	");
};

_AH_Normal = _AH_Normal + ("
	if (("+_kfc_info+" sele>
13:22:39   Error position: <_AH_Normal + ("
	if (("+_kfc_info+" sele>
13:22:39   Error Undefined variable in expression: _ah_normal
13:22:39 File z\addons\dayz_server\antihack\antihack.sqf, line 910
13:22:40 "<Epoch-AH>: Staff client compiled successfully"
13:22:40 "<Epoch-AH>: SERVER: Created 156 safe zone bubbles"
13:22:40 "<Epoch-AH>: SERVER: Processing mission files..."
13:22:40 Error in expression < {_arr set [_i, 0]};
			_file = toArray(preprocessFile _x);

			{_x = _x min 128>
13:22:40   Error position: <preprocessFile _x);

			{_x = _x min 128>
13:22:40   Error preprocessfile: Type Array, expected String

**Comment by BigEgg17** [comment]
> running a 1.0.7 pre-release server, and getting getting a few errors in my RTP :
> 
> 13:22:39 Error in expression < if (str DZE_RestrictSkins != str "+str DZE_RestrictSkins+") then {throw 'DZE_Re>
> 13:22:39 Error position: <DZE_RestrictSkins+") then {throw 'DZE_Re>
> 13:22:39 Error Undefined variable in expression: dze_restrictskins
> 13:22:39 File z\addons\dayz_server\antihack\antihack.sqf, line 892
> 13:22:39 Error in expression <6}]];
> ");
> 
> if (_mic) then {_AH_Normal = _AH_Normal + ("
> [] spawn {
> waitUntil >
> 13:22:39 Error position: <_AH_Normal + ("
> [] spawn {
> waitUntil >
> 13:22:39 Error Undefined variable in expression: _ah_normal
> 13:22:39 File z\addons\dayz_server\antihack\antihack.sqf, line 939
> 13:22:39 ": Normal client compiled successfully"
> 13:22:39 Error in expression <indDisplay 46}]];
> ");
> };
> 
> _AH_Normal = _AH_Normal + ("
> if (("+_kfc_info+" sele>
> 13:22:39 Error position: <_AH_Normal + ("
> if (("+_kfc_info+" sele>
> 13:22:39 Error Undefined variable in expression: _ah_normal
> 13:22:39 File z\addons\dayz_server\antihack\antihack.sqf, line 910
> 13:22:40 ": Staff client compiled successfully"
> 13:22:40 ": SERVER: Created 156 safe zone bubbles"
> 13:22:40 ": SERVER: Processing mission files..."
> 13:22:40 Error in expression < {_arr set [_i, 0]};
> _file = toArray(preprocessFile _x);
> 
> ```
> 		{_x = _x min 128>
> ```
> 
> 13:22:40 Error position: <preprocessFile _x);
> 
> ```
> 		{_x = _x min 128>
> ```
> 
> 13:22:40 Error preprocessfile: Type Array, expected String13:22:39 Error in expression < if (str DZE_RestrictSkins != str "+str DZE_RestrictSkins+") then {throw 'DZE_Re>
> 13:22:39 Error position: <DZE_RestrictSkins+") then {throw 'DZE_Re>
> 13:22:39 Error Undefined variable in expression: dze_restrictskins
> 13:22:39 File z\addons\dayz_server\antihack\antihack.sqf, line 892
> 13:22:39 Error in expression <6}]];
> ");
> 
> if (_mic) then {_AH_Normal = _AH_Normal + ("
> [] spawn {
> waitUntil >
> 13:22:39 Error position: <_AH_Normal + ("
> [] spawn {
> waitUntil >
> 13:22:39 Error Undefined variable in expression: _ah_normal
> 13:22:39 File z\addons\dayz_server\antihack\antihack.sqf, line 939
> 13:22:39 ": Normal client compiled successfully"
> 13:22:39 Error in expression <indDisplay 46}]];
> ");
> };
> 
> _AH_Normal = _AH_Normal + ("
> if (("+_kfc_info+" sele>
> 13:22:39 Error position: <_AH_Normal + ("
> if (("+_kfc_info+" sele>
> 13:22:39 Error Undefined variable in expression: _ah_normal
> 13:22:39 File z\addons\dayz_server\antihack\antihack.sqf, line 910
> 13:22:40 ": Staff client compiled successfully"
> 13:22:40 ": SERVER: Created 156 safe zone bubbles"
> 13:22:40 ": SERVER: Processing mission files..."
> 13:22:40 Error in expression < {_arr set [_i, 0]};
> _file = toArray(preprocessFile _x);
> 
> ```
> 		{_x = _x min 128>
> ```
> 
> 13:22:40 Error position: <preprocessFile _x);
> 
> ```
> 		{_x = _x min 128>
> ```
> 
> 13:22:40 Error preprocessfile: Type Array, expected String

Disable _mev in config.sqf - I will push a compatibility fix for this
