### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cyberdemonv2** [BigEgg17/Epoch-Antihack-Admin-Tools#4]
Found that the following do not work with Epoch 1.0.7 Release:
Adding coins to wallet or bank does nothing,
Selecting player as target and triyng to repair a vehicle does nothing.
Step 3 of install,
In \z\addons\dayz_server\system\scheduler\sched_sync.sqf:

Find:
// RESYNC TIME WITH HIVE DLL SYSTEM CALL  << This line does not exist in the release files.
Below it, add:

if (!isNil "AH_timeOverride") exitWith {objNull};

Dont mean to be an arse, just things i have found so far!

**Comment by MathijsNL** [comment]
> Adding coins to wallet or bank does nothing,

Adding coins works for me. Did you disable the anti-hack thats built in? 

https://github.com/BigEgg17/Epoch-Antihack-Admin-Tools#step-6

**Comment by BigEgg17** [comment]
Resolved here: https://github.com/BigEgg17/Epoch-Antihack-Admin-Tools/commit/5fffb0a1b14ec68cf6ff12a4737f039e784adbc1

**Comment by BigEgg17** [comment]
Sorry, I read the comment and only fixed the coin issue. The others are fixed here: https://github.com/BigEgg17/Epoch-Antihack-Admin-Tools/commit/d6399c7fcfb564197688bd9f61944531f2a22ee0

Thanks and definitely did not come off as an arse! lol
