### ISSUE TITLE
Access to global locks

### ISSUE THREAD

**Issue by ZizionarD** [BigEgg17/Epoch-Antihack-Admin-Tools#6]
Hello! How do I access the global ban system?

**Comment by BigEgg17** [comment]
Set _egb to true in config.sqf and all global bans will be added to ban.txt in server root folder

**Comment by ZizionarD** [comment]
I mean, how to get the login and password for the global ban system?

**Comment by BigEgg17** [comment]
The global ban system is no longer maintained, so only existing bans are sent. Credentials would only send your logs to us for review and since we no longer do this, it would be pointless to hand out credentials.
