### ISSUE TITLE
Suggestion: Skin Preview

### ISSUE THREAD

**Issue by VoltanDan** [BigEgg17/Epoch-Antihack-Admin-Tools#7]
Hey guys,

I would love the ability as an admin to be able to preview skins, so I can see what skins are cool to put in for AI and spawn setups, Infistar used to be able to do it, but I prefer using this admin tool by far.

Just a suggestion, and would be much appreciated :)

Thanks

**Comment by BigEgg17** [comment]
This will likely not be added due to time needed to implement. I believe Choc has posted a public script for viewing skins.

Thanks for the suggestion
