### ISSUE TITLE
Request: Upgraded Vehicles need to be whitelisted

### ISSUE THREAD

**Issue by AirwavesMan** [BigEgg17/Epoch-Antihack-Admin-Tools#8]
Currently upgraded vehicles getting deleted by the Anti Hack if they are not added in the trader configs or the vehicle whitelist array. Could you add a check how we do it in advanced trading? This would add the vehicles to the spawnlist too.

https://github.com/EpochModTeam/DayZ-Epoch/blob/3337c5a74996e374225c341f7af944f7c6646ddb/SQF/dayz_code/actions/AdvancedTrading/functions/z_at_checkArrayInConfig.sqf#L123

**Comment by AirwavesMan** [comment]
Ive just added the wrong link to the main post. Link is updated now.

**Comment by BigEgg17** [comment]
Fixed in commit https://github.com/BigEgg17/Epoch-Antihack-Admin-Tools/commit/5470df94aae9da7d4223b954c10139fa684aa800 @AirwavesMan
