### ISSUE TITLE
Error on every death and godmode wont turn off

### ISSUE THREAD

**Issue by SmokeyBR** [BigEgg17/Epoch-Antihack-Admin-Tools#9]
this error will occur on every player death https://pastebin.com/B9Z8HcmS

Also if u cache godmode, on next login you wont be able to turn it off.

**Comment by BigEgg17** [comment]
Please update to the latest version of the antihack to fix the first player death issue. I will look into the god mode issue

**Comment by BigEgg17** [comment]
@SmokeyBR I could not replicate the issue with god mode. Could you provide steps to reproduce?

**Comment by SmokeyBR** [comment]
i cant get into game right now but will check and let you know on both issues once i am able to.
the godmode issue is not that difficult to reproduce however i did make changes of my own to the code so it could be on my end.

just to make sure you understand the steps
1 - turn on godmode
2 - cache configuration
3 - log out
4 - restart server (prob important step)
5 - log back in
6 - turn off godmode
7 - option should look truned off however godmode will still be enabled

as far as i remember thats it... will report back if something different, once i can get into the game

**Comment by BigEgg17** [comment]
> i cant get into game right now but will check and let you know on both issues once i am able to.
> the godmode issue is not that difficult to reproduce however i did make changes of my own to the code so it could be on my end.
> 
> just to make sure you understand the steps
> 1 - turn on godmode
> 2 - cache configuration
> 3 - log out
> 4 - restart server (prob important step)
> 5 - log back in
> 6 - turn off godmode
> 7 - option should look truned off however godmode will still be enabled
> 
> as far as i remember thats it... will report back if something different, once i can get into the game

I have yet to be able to reproduce this. I am unsure if there is an error on your end with script compatibility, or if my test server with nothing on it is just too speedy.

**Comment by BigEgg17** [comment]
@SmokeyBR would you mind trying the following:

Find this line in antihack.sqf:
```
call AH_fnc_initialize;
```

Replace the line above it with:
```
waitUntil {uiSleep 0.1; (!isNil 'Dayz_loginCompleted' && {!isNil '"+_kfc_keys+"'} && {!isNil 'BIS_fnc_init'})};
```

Let me know if this resolves the issue

**Comment by SmokeyBR** [comment]
sorry i completed forgot about this because i stopped playing.

> I have yet to be able to reproduce this. I am unsure if there is an error on your end with script compatibility, or if my test server with nothing on it is just too speedy.

it could be both, server is modified, as far as log errors go (client and server) i have none.


> Replace the line above it with:
> 
> ```
> waitUntil {uiSleep 0.1; (!isNil 'Dayz_loginCompleted' && {!isNil '"+_kfc_keys+"'} && {!isNil 'BIS_fnc_init'})};
> ```
> 
> Let me know if this resolves the issue

i went in and tried what you said with latest changes of antihack but nothing has changed.

the behavior also happens with cached godmode after dying to AI, i wish i could be of more help, i don't play anymore but if you want me to go after something more specific that can help you, ill gladly do it.
